Fixed build failure in lestrrat/go-jwx due to "Rewrite JWK " changes.
- use go mod
```
$ go mod init github.com/lyokato/goidc
$ go mod tidy
```

- build failed
```
$ go build
crypto/key.go:18:18: undefined: jwk.NewRsaPublicKey
crypto/key.go:41:27: undefined: jwk.RsaPublicKey
```

See: https://github.com/lestrrat/go-jwx/commit/72867763d6cbf58bf3d7b4c8a40e971ddd69325c